### ISSUE TITLE
About the legend

### ISSUE THREAD

**Issue by WenliZou** [sdesabbata/BivariateTMap#1]
Hey,

Thanks for creating the R resource for getting a bivariate map based on tmap. I just found a small mistake maybe. The y axis is not going from shallow color to darker which should indicate smaller number to larger one(the pink line). It reversed as the darker color represents a smaller number and I found the problem is caused by the line

  bivmap_sdf$bicat <- bivmap_sdf$xcat + (3 * (bivmap_sdf$ycat - 1))

And I changed it to 
 bivmap_sdf$bicat <- bivmap_sdf$xcat + (3 * (3-bivmap_sdf$ycat))
and it works well. 

Could you please check it and to see whether I understand the code correctly?

Thanks

**Comment by stefdesabbata** [comment]
Apologies for the late reply.

The code seems to work fine. Could you provide a specific example?

Thank you so much.
All the best.
