### ISSUE TITLE
Not sure where this error is coming from

### ISSUE THREAD

**Issue by jeffcsauer** [sdesabbata/BivariateTMap#2]
Hi there - 

Thank you so much for the script! It's quite handy. I've been able to render a few plots; however, some of them throw the following errors. I know this example isn't exactly reproducible, but any direction on what this error might mean could allow me to debug.

![image](https://user-images.githubusercontent.com/31426294/65783593-19d26c80-e11e-11e9-87f9-9154dbd44b45.png)

**Update:** sometimes re-running the command will allow the plot to render. Is this related to plot margins or some internal R setting? Script seems to be running perfectly fine!

**Comment by stefdesabbata** [comment]
Thanks for the message and the update. I am not sure what's causing the issue, but there seems to be an related open issue in ggplot2, so it is most probably related to some issue in the libraries used by the script.

See https://github.com/tidyverse/ggplot2/issues/3538
